require: rubocop-rspec

#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - log/**/*

Rails:
  Enabled: true

# I don't understand it
Style/ExpandPathArguments:
  Enabled: false

# Ruby 3.0 feature related stuff, will see later
Style/FrozenStringLiteralComment:
  EnforcedStyle: never


Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'lib/tasks/watch.rake'
    - 'lib/tasks/local_watch.rake'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/models/call_result_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false


# Do not force documentation at the top of classes
Documentation:
  Enabled: false

# Buggy... empty lines are not accepted sometimes...
Layout/EmptyLinesAroundArguments:
  Exclude:
    - 'app/models/endpoint.rb'

Layout/MultilineOperationIndentation:
  Exclude:
    - 'config/deploy.rb'

Metrics/AbcSize:
 Max: 25

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
     Max: 5

RSpec/AnyInstance:
  Enabled: false

# We don't use spies
RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/watch_spec.rb'
    - 'spec/tasks/refill_database_spec.rb'
