require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - vendor/**/*
    - log/**/*

Rails:
  Enabled: true

# only used in console no need to log
Rails/Output:
  Exclude:
    - 'lib/tasks/project_init.rake'
    - 'config/deploy.rb'

Rails/TimeZone:
  Enabled: false

# Ruby 3.0 feature related stuff, will see later
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# Do not force use of fail or raise only both have their use
Style/SignalException:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

# Do not force documentation at the top of classes
Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Exclude:
    - 'config/deploy.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile' # mono bloc inside...

Metrics/LineLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/MultipleExpectations:
     Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/SubjectStub:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
