language: ruby
rvm:
  2.4.2
env:
  global:
    - CC_TEST_REPORTER_ID=f7751bd1159e29027bc622dfc71bebdd795c67f0cbb9c6ebc033ba94479f6b3a
services:
  - postgresql
before_script:
  - psql -c 'create database watchdoge_test_travis;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake dev:secrets
  - RAILS_ENV=test bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec spec --format documentation --color
  - bundle exec rspec spec --format documentation --color --tag very_long_test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT