defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10
  username: watchdoge_development
  password: password

development:
  database: watchdoge_development
  <<: *defaults

test:
  database: watchdoge_test
  <<: *defaults

production:
  database: watchdoge_production
  <<: *defaults

sandbox:
  database: watchdoge_sandbox
  <<: *defaults

staging:
  database: watchdoge_staging
  <<: *defaults
