enabled: true
source: 'watchdoge_development'
record_enabled: false
job_enabled: true
backtrace: false
controller_enabled: true
log_controller_parameters: true
mailer_enabled: false
view_enabled: false
suppress_app_log: false
