defaults: &DEFAULTS
  apie_token: such_token
  apie_base_uri: 'api-sandbox.apientreprise.fr'
  secret_key_base: 41b60bfad06bbcf0262cb68aa77ddb9fc56d9a39a2591dd32a7d3be5724ed4fb10a20f408b6dcc7f66bfc6b8fa8eaf39b0e4eff77003e2e9db51a794c84b5d8e

sandbox:
  <<: *DEFAULTS
development:
  <<: *DEFAULTS
test:
  <<: *DEFAULTS
production:
  <<: *DEFAULTS
